In [1]:
from pathlib import Path


In [2]:
base_dir=Path.cwd()
data_dir=base_dir/'data'/'input.txt'


In [3]:
data_dir

WindowsPath('c:/Users/beugre niamba/Desktop/Mini_gpt/mini_gpt/data/input.txt')

In [4]:
with open(data_dir,'r') as f:
    text=f.read()
    
print(text[:200])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you


In [5]:
test=text[:30]

In [6]:
chars=sorted(set(text))

In [7]:
i=range(len(chars))

In [8]:
liste=[1,2,3]
for i,val in enumerate(liste):
    print(f'{i}:{val}')

0:1
1:2
2:3


In [9]:
chars
char_to_int={val:i for i,val in enumerate(chars)}
int_to_char={i:val for i,val in enumerate(chars)}

In [10]:
int_to_char

{0: '\n',
 1: ' ',
 2: '!',
 3: '$',
 4: '&',
 5: "'",
 6: ',',
 7: '-',
 8: '.',
 9: '3',
 10: ':',
 11: ';',
 12: '?',
 13: 'A',
 14: 'B',
 15: 'C',
 16: 'D',
 17: 'E',
 18: 'F',
 19: 'G',
 20: 'H',
 21: 'I',
 22: 'J',
 23: 'K',
 24: 'L',
 25: 'M',
 26: 'N',
 27: 'O',
 28: 'P',
 29: 'Q',
 30: 'R',
 31: 'S',
 32: 'T',
 33: 'U',
 34: 'V',
 35: 'W',
 36: 'X',
 37: 'Y',
 38: 'Z',
 39: 'a',
 40: 'b',
 41: 'c',
 42: 'd',
 43: 'e',
 44: 'f',
 45: 'g',
 46: 'h',
 47: 'i',
 48: 'j',
 49: 'k',
 50: 'l',
 51: 'm',
 52: 'n',
 53: 'o',
 54: 'p',
 55: 'q',
 56: 'r',
 57: 's',
 58: 't',
 59: 'u',
 60: 'v',
 61: 'w',
 62: 'x',
 63: 'y',
 64: 'z'}

In [11]:
test

'First Citizen:\nBefore we proce'

In [12]:
tokens=[ char_to_int[c] for c in text]

In [13]:
tokens

[18,
 47,
 56,
 57,
 58,
 1,
 15,
 47,
 58,
 47,
 64,
 43,
 52,
 10,
 0,
 14,
 43,
 44,
 53,
 56,
 43,
 1,
 61,
 43,
 1,
 54,
 56,
 53,
 41,
 43,
 43,
 42,
 1,
 39,
 52,
 63,
 1,
 44,
 59,
 56,
 58,
 46,
 43,
 56,
 6,
 1,
 46,
 43,
 39,
 56,
 1,
 51,
 43,
 1,
 57,
 54,
 43,
 39,
 49,
 8,
 0,
 0,
 13,
 50,
 50,
 10,
 0,
 31,
 54,
 43,
 39,
 49,
 6,
 1,
 57,
 54,
 43,
 39,
 49,
 8,
 0,
 0,
 18,
 47,
 56,
 57,
 58,
 1,
 15,
 47,
 58,
 47,
 64,
 43,
 52,
 10,
 0,
 37,
 53,
 59,
 1,
 39,
 56,
 43,
 1,
 39,
 50,
 50,
 1,
 56,
 43,
 57,
 53,
 50,
 60,
 43,
 42,
 1,
 56,
 39,
 58,
 46,
 43,
 56,
 1,
 58,
 53,
 1,
 42,
 47,
 43,
 1,
 58,
 46,
 39,
 52,
 1,
 58,
 53,
 1,
 44,
 39,
 51,
 47,
 57,
 46,
 12,
 0,
 0,
 13,
 50,
 50,
 10,
 0,
 30,
 43,
 57,
 53,
 50,
 60,
 43,
 42,
 8,
 1,
 56,
 43,
 57,
 53,
 50,
 60,
 43,
 42,
 8,
 0,
 0,
 18,
 47,
 56,
 57,
 58,
 1,
 15,
 47,
 58,
 47,
 64,
 43,
 52,
 10,
 0,
 18,
 47,
 56,
 57,
 58,
 6,
 1,
 63,
 53,
 59,
 1,
 49,
 52,
 53,
 61,
 1,
 15,
 39,
 47,

In [14]:
import torch

In [15]:
data = torch.tensor(tokens, dtype=torch.long)

In [16]:
n=int(0.9*len(data))

train_data=data[:n]
test_data=data[n:]

In [17]:
block_size=256
batch_size=32

In [18]:
i=torch.randint(len(data) - block_size, (batch_size,))

In [20]:
i

tensor([ 118470,  968718,  512866,  486693,  596887,  511336,  859052,    3080,
         198476,  235651,  702393, 1086782,  313865, 1042899,  774033,  192611,
         245173,  773440,  700995,  948886,  679889,  197036,  868246,  778612,
         962318,  385216,  157905,  466226,  277877,  282191,  347191,  794837])

In [31]:
data

tensor([18, 47, 56,  ..., 45,  8,  0])

In [27]:
indices = torch.randint(len(data) - block_size, (batch_size,))
x = torch.stack([data[i : i + block_size] for i in indices])
y = torch.stack([data[i+1 : i + block_size + 1] for i in indices])

In [34]:
indices

tensor([714903,  74158, 239357, 644541, 457480, 445402, 801243,  56777, 285283,
        818584, 950379, 537899,  91052,  36925, 677504, 142286, 133068, 744456,
         10942, 100851, 796272, 293781, 716606, 404452, 382750, 262281, 258643,
        108814, 308547,  57444,   8049, 356879])

In [33]:
x.shape

torch.Size([32, 256])

In [32]:
y

tensor([[43, 58,  1,  ..., 43, 56, 12],
        [43,  1, 53,  ..., 59, 42, 45],
        [63, 53, 59,  ..., 42, 57,  6],
        ...,
        [57, 43,  1,  ..., 42,  1, 15],
        [46,  1, 61,  ..., 39, 58,  5],
        [31, 10,  0,  ..., 54, 43, 39]])